### ISSUE TITLE
Prospector: f-string invalid syntax

### ISSUE THREAD

**Issue by mxlei01** [codacy/codacy-pylint#42]
I'm getting an invalid syntax on prospector even though I added a codacy.yml file:

```
engines:
 prospector:
   enabled: true
   python_version: 3
```
